name: "Run go checks"
description: "Runs go code checks (tests, linters, ...)"

inputs:
  git-user:
    required: true
    description: "Git user name"
  git-token:
    required: true
    description: "Git user token"

runs:

  using: composite

  steps:
    # Downloads a copy of the code in your repository before running CI tests
    - name: Set up go
      uses: actions/setup-go@v4.0.1
      with:
        go-version-file: 'scribe-service/go.mod'

    - name: Configure git for private modules
      shell: bash
      env:
        TOKEN: ${{ inputs.git-token }}
        USERNAME: ${{ inputs.git-user }}
        GOPRIVATE: "github.com/scribe-security/*"
      run: git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: check tidy
      shell: bash
      run: |
        (cd scribe-service && go mod tidy)
        make git-status

    - name: check build
      shell: bash
      run: make build-scribe-cmd

    # - name: check formatters
    #   shell: bash
    #   run: |
    #     go install github.com/daixiang0/gci@v0.9.0
    #     make format-go
    #     make git-status

#    - name: golangci-lint
#      uses: golangci/golangci-lint-action@v3.4.0
#      continue-on-error: true
#      with:
#        working-directory: scribe-service
#        version: v1.51.1
#        skip-cache: true
#        args: --timeout 10m
#
