// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: github_app.sql

package db

import (
	"context"
)

const disableGithubInstallation = `-- name: DisableGithubInstallation :exec
UPDATE app."Team"
set "gitHubAppInstallationActive" = FALSE
WHERE "gitHubAppInstallationId" = $1::bigint
`

func (q *Queries) DisableGithubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.exec(ctx, q.disableGithubInstallationStmt, disableGithubInstallation, installationID)
	return err
}

const enableGithubInstallation = `-- name: EnableGithubInstallation :exec
UPDATE app."Team"
set "gitHubAppInstallationActive" = TRUE
WHERE "gitHubAppInstallationId" = $1::bigint
`

func (q *Queries) EnableGithubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.exec(ctx, q.enableGithubInstallationStmt, enableGithubInstallation, installationID)
	return err
}
