"""baseimage

Revision ID: 109987869046
Revises: 9493aebc70da
Create Date: 2023-05-11 10:13:45.133054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "109987869046"
down_revision = "9493aebc70da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "RegistryImage",
        sa.Column("is_base_image", sa.Boolean(), nullable=True),
        schema="osint",
    )
    op.create_index(
        "RegistryImage_is_base_image_idx",
        "RegistryImage",
        ["is_base_image"],
        unique=False,
        schema="osint",
    )
    op.alter_column(
        "RegistryScanConfig",
        "repos_filter",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=False,
        schema="osint",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "RegistryScanConfig",
        "repos_filter",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=True,
        schema="osint",
    )
    op.drop_index("RegistryImage_is_base_image_idx", table_name="RegistryImage", schema="osint")
    op.drop_column("RegistryImage", "is_base_image", schema="osint")
    # ### end Alembic commands ###
