"""

Revision ID: 29dc73969f5c
Revises: cc5ffb126895
Create Date: 2023-06-08 13:09:42.577893

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = "29dc73969f5c"
down_revision = "cc5ffb126895"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    osint_cveimpact = PGMaterializedView(
        schema="osint",
        signature="CveImpact",
        definition='SELECT osint."Vulnerability".id AS vulnerability_id, osint."Vulnerability".severity AS severity, osint."Attestation".id AS attestation_id, osint."Attestation".logical_app, osint."Attestation".logical_app_version, osint."Attestation".context ->> \'input_tag\' AS anon_1, osint."Attestation"."targetName", osint."Component".id AS component_id, osint."Component".name, osint."Component".version, \n    array_to_string(\n               ARRAY(SELECT jsonb_array_elements_text(osint."Attestation".context -> \'labels\') AS jsonb_array_elements_text),\n               \',\'::text)\n    _labels, osint."LatestPackageVersions".version AS latest_package_version, osint."Vulnerability"."cvssScore", round(CAST(osint."Vulnerability"."epssProbability" * 100 AS NUMERIC), 6) AS "epssProbability", osint."Vulnerability"."publishedOn", osint.vul_advisory."hyperLinks", osint.vul_advisory.source \nFROM osint."Attestation" JOIN osint."AttestationComponent" ON osint."Attestation".id = osint."AttestationComponent".attestation JOIN osint."Component" ON osint."Component".id = osint."AttestationComponent".component JOIN osint."VulComponent" ON osint."Component".id = osint."VulComponent".component JOIN osint."Vulnerability" ON osint."Vulnerability".id = osint."VulComponent"."vulId" JOIN osint.vul_advisory ON osint.vul_advisory.vul_id = osint."Vulnerability".id LEFT OUTER JOIN osint."LatestPackageVersions" ON lower(osint."Component".name) = lower(osint."LatestPackageVersions".name) \nWHERE (osint."Component"."group" NOT IN (\'file\', \'deb\', \'layer\', \'syft\'))',
        with_data=False,
    )
    op.create_entity(osint_cveimpact)

    op.execute(
        """
    create unique index on osint."CveImpact" (attestation_id, component_id, vulnerability_id)
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    osint_cveimpact = PGMaterializedView(
        schema="osint",
        signature="CveImpact",
        definition='SELECT osint."Vulnerability".id AS vulnerability_id, osint."Vulnerability".severity AS severity, osint."Attestation".id AS attestation_id, osint."Attestation".logical_app, osint."Attestation".logical_app_version, osint."Attestation".context ->> \'input_tag\' AS anon_1, osint."Attestation"."targetName", osint."Component".id AS component_id, osint."Component".name, osint."Component".version, \n    array_to_string(\n               ARRAY(SELECT jsonb_array_elements_text(osint."Attestation".context -> \'labels\') AS jsonb_array_elements_text),\n               \',\'::text)\n    _labels, osint."LatestPackageVersions".version AS latest_package_version, osint."Vulnerability"."cvssScore", round(CAST(osint."Vulnerability"."epssProbability" * 100 AS NUMERIC), 6) AS "epssProbability", osint."Vulnerability"."publishedOn", osint.vul_advisory."hyperLinks", osint.vul_advisory.source \nFROM osint."Attestation" JOIN osint."AttestationComponent" ON osint."Attestation".id = osint."AttestationComponent".attestation JOIN osint."Component" ON osint."Component".id = osint."AttestationComponent".component JOIN osint."VulComponent" ON osint."Component".id = osint."VulComponent".component JOIN osint."Vulnerability" ON osint."Vulnerability".id = osint."VulComponent"."vulId" JOIN osint.vul_advisory ON osint.vul_advisory.vul_id = osint."Vulnerability".id LEFT OUTER JOIN osint."LatestPackageVersions" ON lower(osint."Component".name) = lower(osint."LatestPackageVersions".name) \nWHERE (osint."Component"."group" NOT IN (\'file\', \'deb\', \'layer\', \'syft\'))',
        with_data=False,
    )

    op.drop_entity(osint_cveimpact)

    # ### end Alembic commands ###
