"""vul_component_refresh

Revision ID: 45ce892ef997
Revises: 484ad3956ae3
Create Date: 2023-05-31 09:54:31.100415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45ce892ef997"
down_revision = "484ad3956ae3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "VulComponent",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        schema="osint",
    )
    op.add_column(
        "VulComponent",
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        schema="osint",
    )
    op.create_index(
        "VulComponent_created_deleted",
        "VulComponent",
        ["created", "deleted"],
        unique=False,
        schema="osint",
    )
    op.create_index(
        "VulComponent_deleted",
        "VulComponent",
        ["deleted"],
        unique=False,
        schema="osint",
    )
    op.drop_constraint(constraint_name="VulComponent_pkey", table_name="VulComponent", schema="osint")
    op.create_primary_key(
        constraint_name="VulComponent_pkey",
        table_name="VulComponent",
        columns=["component", "vulId", "created"],
        schema="osint",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name="VulComponent_pkey", table_name="VulComponent", schema="osint")
    op.create_primary_key(
        constraint_name="VulComponent_pkey",
        table_name="VulComponent",
        columns=["component", "vulId"],
        schema="osint",
    )
    op.drop_index("VulComponent_deleted", table_name="VulComponent", schema="osint")
    op.drop_index("VulComponent_created_deleted", table_name="VulComponent", schema="osint")
    op.drop_column("VulComponent", "deleted", schema="osint")
    op.drop_column("VulComponent", "created", schema="osint")
    # ### end Alembic commands ###
