"""

Revision ID: 5edea64a5480
Revises: 6172bb0020e0
Create Date: 2023-06-06 14:53:11.507097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5edea64a5480"
down_revision = "6172bb0020e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Scorecard",
        sa.Column(
            "project_name",
            sa.Text(),
            sa.Computed("substr(repo_name, (strpos(repo_name, '/'::text) + 1))", persisted=True),
            nullable=True,
        ),
        schema="osint",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Scorecard", "project_name", schema="osint")
    # ### end Alembic commands ###
