"""attestation app and tool

Revision ID: 6172bb0020e0
Revises: 45ce892ef997
Create Date: 2023-06-06 11:12:27.132380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6172bb0020e0"
down_revision = "40b5d31652ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Attestation", sa.Column("logical_app", sa.Text(), nullable=True), schema="osint")
    op.add_column("Attestation", sa.Column("logical_app_version", sa.Text(), nullable=True), schema="osint")
    op.add_column("Attestation", sa.Column("tool", sa.Text(), nullable=True), schema="osint")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Attestation", "tool", schema="osint")
    op.drop_column("Attestation", "logical_app_version", schema="osint")
    op.drop_column("Attestation", "logical_app", schema="osint")
    # ### end Alembic commands ###
