"""scorecard

Revision ID: 9efd4f15f588
Revises: 36740d29f9de
Create Date: 2023-03-22 07:10:19.887653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.mock import MockConnection

# revision identifiers, used by Alembic.
revision = "9efd4f15f588"
down_revision = "b98e20345719"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    insp: sa.engine.reflection.Inspector | None = None
    conn = op.get_bind()
    if not isinstance(conn, MockConnection):
        insp = sa.engine.reflection.Inspector.from_engine(conn)
    if insp is None or not insp.has_table("PackageToVersion", schema="osint"):
        op.create_table(
            "PackageToVersion",
            sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column("system", sa.Text(), nullable=True),
            sa.Column("name", sa.Text(), nullable=False),
            sa.Column("version", sa.Text(), nullable=True),
            sa.Column("project_type", sa.Text(), nullable=True),
            sa.Column("project_name", sa.Text(), nullable=True),
            sa.Column("snapshotAt", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            schema="osint",
        )
    if insp is None or not insp.has_table("Scorecard", schema="osint"):
        op.create_table(
            "Scorecard",
            sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column("date", sa.DateTime(), nullable=False),
            sa.Column("repo_name", sa.Text(), nullable=False),
            sa.Column("score", sa.Float(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            schema="osint",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # do not drop it
    # op.drop_table("Scorecard")
    # op.drop_table("PackageToVersion")
    # ### end Alembic commands ###
    pass
