"""scorecard extra

Revision ID: cc5ffb126895
Revises: 6088dff7ce0d
Create Date: 2023-06-08 11:18:21.811140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc5ffb126895"
down_revision = "6088dff7ce0d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Scorecard", sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema="osint"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Scorecard", "extra", schema="osint")
    # ### end Alembic commands ###
