basePath: /
consumes:
    - application/json
definitions:
    AllContext:
        properties:
            actor:
                type: string
                x-go-name: Actor
            app_name:
                type: string
                x-go-name: ApplicationName
            app_version:
                type: string
                x-go-name: ApplicationVersion
            build_num:
                type: string
                x-go-name: BuildNum
            content_type:
                type: string
                x-go-name: ContentType
            context_type:
                type: string
                x-go-name: ContextType
            dir_id:
                type: string
                x-go-name: DirIDField
            dir_path:
                type: string
                x-go-name: DirPathField
            env:
                additionalProperties:
                    type: string
                type: object
                x-go-name: Envs
            file_id:
                type: string
                x-go-name: FileIDField
            file_path:
                type: string
                x-go-name: FilePathField
            git_branch:
                type: string
                x-go-name: GitBranch
            git_commit:
                type: string
                x-go-name: GitCommit
            git_ref:
                type: string
                x-go-name: GitRef
            git_tag:
                type: string
                x-go-name: GitTag
            git_url:
                type: string
                x-go-name: GitURL
            hostname:
                type: string
                x-go-name: Hostname
            image_name:
                type: string
                x-go-name: ImageName
            imageID:
                type: string
                x-go-name: ImageID
            imageTag:
                items:
                    type: string
                type: array
                x-go-name: Tags
            input_name:
                type: string
                x-go-name: InputNameF
            input_scheme:
                type: string
                x-go-name: InputSchemeF
            input_tag:
                type: string
                x-go-name: InputTagF
            job_name:
                type: string
                x-go-name: JobName
            labels:
                items:
                    type: string
                type: array
                x-go-name: Labels
            name:
                type: string
                x-go-name: NameField
            pipeline_name:
                type: string
                x-go-name: Pipeline
            predicate_type:
                type: string
                x-go-name: PredicateType
            product_version:
                type: string
                x-go-name: VersionField
            repoDigest:
                items:
                    type: string
                type: array
                x-go-name: RepoDigest
            run_id:
                type: string
                x-go-name: RunID
            sbomgroup:
                type: string
                x-go-name: Group
            sbomhashs:
                items:
                    type: string
                type: array
                x-go-name: Hashs
            sbomname:
                type: string
                x-go-name: Name
            sbompurl:
                type: string
                x-go-name: Purl
            sbomversion:
                type: string
                x-go-name: Version
            target_git_branch:
                type: string
                x-go-name: GitBranchField
            target_git_commit:
                type: string
                x-go-name: GitCommitField
            target_git_ref:
                type: string
                x-go-name: GitRefField
            target_git_tag:
                type: string
                x-go-name: GitTagField
            target_git_url:
                type: string
                x-go-name: GitURLField
            target_type:
                type: string
                x-go-name: Type
            timestamp:
                type: string
                x-go-name: TimestampField
            user:
                type: string
                x-go-name: User
            workflow:
                type: string
                x-go-name: Workflow
        type: object
        x-go-package: github.com/scribe-security/cocosign/storer/evidence
    Attestation:
        properties:
            alerted:
                type: boolean
                x-go-name: Alerted
            contenttype:
                type: string
                x-go-name: ContentType
            context:
                type: object
                x-go-name: Context
            contexttype:
                type: string
                x-go-name: ContextType
            deleted:
                type: boolean
                x-go-name: Deleted
            id:
                format: int64
                type: integer
                x-go-name: ID
            job_ids:
                items:
                    type: string
                type: array
                x-go-name: JobIds
            key:
                type: string
                x-go-name: Key
            license:
                type: string
                x-go-name: License
            pipelinerun:
                format: int64
                type: integer
                x-go-name: PipelineRun
            sigstatus:
                type: string
                x-go-name: SigStatus
            state:
                $ref: '#/definitions/Typeevidencestatus'
            targetname:
                type: string
                x-go-name: TargetName
            targettype:
                type: string
                x-go-name: TargetType
            teamid:
                format: int64
                type: integer
                x-go-name: TeamID
            timestamp:
                $ref: '#/definitions/NullTime'
            txt:
                x-go-name: Txt
            userid:
                format: int64
                type: integer
                x-go-name: UserID
        type: object
        x-go-package: github.com/scribe-security/scribe2/scribe-service/internal/domain
    FinishUploadEvidence:
        properties:
            error:
                description: Error message, if not nil, transfer will be marked as failed
                type: string
                x-go-name: Error
            file_id:
                description: FileID of transfer, can be used to link with other objects
                format: int64
                type: integer
                x-go-name: FileID
        type: object
        x-go-package: github.com/scribe-security/scribe2/scribe-service/internal/domain
    NullTime:
        description: |-
            NullTime implements the Scanner interface so
            it can be used as a scan destination, similar to NullString.
        properties:
            Time:
                format: date-time
                type: string
            Valid:
                type: boolean
        title: NullTime represents a time.Time that may be null.
        type: object
        x-go-package: database/sql
    Typeevidencestatus:
        type: string
        x-go-package: github.com/scribe-security/scribe2/scribe-service/internal/domain
    UploadEvidence:
        description: UploadEvidence action parameters
        properties:
            content_type:
                description: ContentType file content type
                type: string
                x-go-name: ContentType
            context:
                description: Context additional file metadata
                type: object
                x-go-name: ContextData
            context_type:
                description: ContextType file context type
                type: string
                x-go-name: ContextType
            key:
                description: Key is a file name path, it should be uniq
                type: string
                x-go-name: Key
        type: object
        x-go-package: github.com/scribe-security/scribe2/scribe-service/internal/domain
host: localhost:4000
info:
    contact:
        email: ori@scribesecurity.com
        name: Ori Avraham
    license:
        name: MIT
        url: http://opensource.org/licenses/MIT
    title: Scribe API.
    version: 0.0.1
paths:
    /evidence:
        post:
            consumes:
                - application/json
            description: |-
                This endpoint is used to upload evidence to the cloud storage.
                It returns a presigned URL to upload the file content.
                After uploading the file content, the client should call `/evidence/finish`.
            operationId: uploadEvidenceAction
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/UploadEvidence'
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/createEvidenceOutput'
                "400":
                    $ref: '#/responses/errorResponse'
                "403":
                    $ref: '#/responses/errorResponse'
            schemes:
                - https
            security:
                - JWT: []
            summary: Create presigned URL to POST file content.
            tags:
                - evidence
    /evidence/{file_id}:
        delete:
            consumes:
                - application/json
            description: <p>Delete evidence object by <b>file_id</b>.
            operationId: deleteEvidenceAction
            parameters:
                - description: FileID if not null used to delete only one file
                  format: int64
                  in: path
                  name: file_id
                  required: true
                  type: integer
                  x-go-name: FileID
            produces:
                - application/json
            responses:
                "200":
                    description: ""
                "400":
                    $ref: '#/responses/errorResponse'
                "403":
                    $ref: '#/responses/errorResponse'
            schemes:
                - https
            security:
                - JWT: []
            summary: Delete evidence object.
            tags:
                - evidence
        get:
            consumes:
                - application/json
            description: |-
                This endpoint is used to upload evidence to the cloud storage.
                It returns a presigned URL to upload the file content.
                After uploading the file content, the client should call `/evidence/finish`.
            operationId: downloadEvidenceAction
            parameters:
                - description: FileID if not null used to delete only one file
                  format: int64
                  in: path
                  name: file_id
                  required: true
                  type: integer
                  x-go-name: FileID
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/getEvidenceDownloadOutput'
                "400":
                    $ref: '#/responses/errorResponse'
                "403":
                    $ref: '#/responses/errorResponse'
            schemes:
                - https
            security:
                - JWT: []
            summary: Create presigned URL to POST file content.
            tags:
                - evidence
    /evidence/finish:
        post:
            consumes:
                - application/json
            description: Push file transfer result after POST file content.
            operationId: finishUploadEvidenceAction
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/FinishUploadEvidence'
            produces:
                - application/json
            responses:
                "200":
                    description: ""
                "400":
                    $ref: '#/responses/errorResponse'
                "403":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            schemes:
                - https
            security:
                - JWT: []
            summary: Mark file transfer as finished.
            tags:
                - evidence
    /evidence/list:
        post:
            consumes:
                - application/json
            operationId: ListEvidenceAction
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/AllContext'
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/listEvidenceView'
                "400":
                    $ref: '#/responses/errorResponse'
                "403":
                    $ref: '#/responses/errorResponse'
            schemes:
                - https
            security:
                - JWT: []
            summary: Get a list of processes for specific queries.
            tags:
                - evidence
produces:
    - application/json
responses:
    createEvidenceOutput:
        description: CreateEvidenceOutput response for CreateEvidence request
        headers:
            file_id:
                description: FileID for the internal objects link
                format: int64
                type: integer
            presigned_url:
                description: PresignedURL to upload the file directly to the cloud storage
                type: string
    errorResponse:
        description: ResponseError represent the reseponse error struct
        headers:
            message:
                type: string
            status:
                format: int64
                type: integer
    getEvidenceDownloadOutput:
        description: GetEvidenceDownloadOutput response for getEvidenceDownloadOutput request.
        headers:
            presigned_url:
                description: PresignedURL to download the file directly from the cloud storage
                type: string
    listEvidenceView:
        description: ListEvidenceViewOutput details a list of the queried evidence
        schema:
            properties:
                evidences:
                    items:
                        $ref: '#/definitions/Attestation'
                    type: array
                    x-go-name: Evidences
            type: object
schemes:
    - http
    - https
security:
    - JWT: []
securityDefinitions:
    JWT:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
