name: Destroy Test AWS Infrastructure

run-name: Destroy test environment from ${{ github.ref_name }} branch

concurrency: concurrency-test

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:    
  Terraform-Destroy:
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.SCRIBE2_GITHUB_ROLE }}
          role-session-name: Github
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install tf
        uses: hashicorp/setup-terraform@v2

      - name: Terraform destroy
        run: |
          cd infra
          terraform get -update
          terraform init -upgrade
          terraform fmt
          terraform workspace select test
          terraform destroy -auto-approve -var-file test.tfvars 
      