name:  scribe_github_workflow

on: push

jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    steps:

    - uses: scribe-security/action-bom@master
      with:
        target: ./
        format: attest
        scribe-enable: true
        product-key: "Nadya_Test"
        scribe-client-id: 9y9svuyNTsOrkE6eZ5fsncsHu4xHijLb
        scribe-client-secret: fB4--LY0PlzcnRXN5u-Ns84HrGOPHUusD38ATBU3iJ2XrBymaAnrIqGIwQsOJtve

    - uses: scribe-security/action-verify@master
      with:
        target: ./
        format: attest
        scribe-enable: true
        product-key: "Nadya_Test"
        scribe-client-id: 9y9svuyNTsOrkE6eZ5fsncsHu4xHijLb
        scribe-client-secret: fB4--LY0PlzcnRXN5u-Ns84HrGOPHUusD38ATBU3iJ2XrBymaAnrIqGIwQsOJtve

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate SLSA provenance statement
      id: valint_slsa_statement
      uses: scribe-security/action-bom@master
      with:
        target: mongo-express:1.0.0-alpha.4
        format: statement-slsa

    - uses: actions/upload-artifact@v2
      with:
        name: provenance
        path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
