name: tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Label of the container job
  check-python:
    runs-on: ubuntu-latest

    services:

      postgres:

        image: postgres:13

        env:
          POSTGRES_PASSWORD: airflow
          POSTGRES_USER: airflow
          POSTGRES_PORT: 5432
          POSTGRES_DB: airflow
        ports:
          - 5432:5432
          # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run checks
        uses: ./.github/actions/python-checks
        with:
          postgres-connection-string: postgres://airflow:airflow@localhost:5432/airflow

  check-go:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run checks
        uses: ./.github/actions/go-checks
        with:
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_PERSONAL_TOKEN }}

